# Generated by Django 5.1.5 on 2025-03-22 08:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogtagpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='content',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('code', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 4: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 5: ('wagtail.blocks.StructBlock', [[('language', 3), ('code', 4)]], {'label': 'Code Block'})}, null=True),
        ),
    ]
