# Generated by Django 5.1.5 on 2025-03-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpostpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostpage',
            name='body',
        ),
    ]
