# Generated by Django 5.1.5 on 2026-02-10 04:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_remove_blogpostpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("image", 2),
                    ("code", 5),
                    ("raw_html", 6),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"form_classname": "title"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    4: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"identifier": "code", "label": "Code"},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 3), ("code", 4)]],
                        {"label": "Code Block"},
                    ),
                    6: ("wagtail.blocks.RawHTMLBlock", (), {"label": "Raw HTML"}),
                },
                null=True,
            ),
        ),
    ]
