# Generated by Django 5.1.5 on 2026-02-10 05:18

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_blogpostpage_content"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogOnlyIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "verbose_name": "Blog Post Index Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ExplainerIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "verbose_name": "Explainer Index Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AddField(
            model_name="blogpostpage",
            name="post_type",
            field=models.CharField(
                choices=[("blog", "Blog Post"), ("explainer", "Explainer")],
                default="blog",
                help_text="Type of post",
                max_length=20,
            ),
        ),
    ]
